inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/compat-rubocop-0_51/style/.rubocop.ribose.yml
  # Living on the edge:
  # - https://raw.githubusercontent.com/riboseinc/oss-guides/master/style/.rubocop.ribose.yml
AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
Rails:
  Enabled: true
