name: Propagate to mirrors

on: [push]

env:
  ID_RSA_PUB: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCi4se5HxHHRvKtRiU4/nDy0uobxbDdKyhMco2weBPiczp5/BJXeUWyklHioy7FxaM2zSCtfhsFKCQ/iG8pNT5qaJ+KsCQYOiPhsAad42QYbMY4EbhaDxrLRDnarcrGX1yAmOZXSL1ppUTnlGVOTYPKOrBohTeY4A+QhyYHLpKeNjHjKUFs+7QC3zQtl6sz2Mkh2N4gft78kimAyAqy+W3MLsIgIsjrIIh/qmo8ow9+toEf9bmlhyk/iCEQ0HMYa7h+eF7M9nxiH/Og8NdVEYxz7fYC8WfCKRWoGcCfPImDoqKKdprYNGWVHkGSsEWsCUE24CHujBGU/IFGaSADhkX5gFNmSsps+r8EGG4AuUgE7ZE6rYWCaUmbBMXOAD+BBmBFAL1Roqilq/W4HfPPVLZO1SAyUNKMFZxu0DBeSM3ttIdcetisf5YOAjZ5+XDMKxsbrQ+ZyIqwn7cXPJxeChJImCG+YMn+NLw94jD042uB4+HWOO7oFrUfn68A4SBsdcb7mMVXL5CcPqTQjmRVYmkNGfwGfDOCgXzuDJ8relS9QkjaBgh0lWQAPQjtph83x9WdUiJaS+A0RrMaN9AyRk8E8EQKbFgOXK368l1dy+FsHWsKA/r9EM3auc2TliRyYurLK1jC5x4A/oyshl3N3KR48rpX9Kq4qUMFo589/q68BQ== oss-guides@ribose.com"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.repository == 'riboseinc/oss-guides'

    steps:
      - uses: actions/checkout@v1

      - uses: shimataro/ssh-key-action@v1.5.0
        with:
          private-key: ${{ secrets.ID_RSA }}
          public-key: ${{ env.ID_RSA_PUB }}

      - name: Propagate to Metanorma
        run: git push --mirror "${TARGET}"
        shell: bash
        env:
          TARGET: "git@github.com:metanorma/oss-guides.git"
